In [2]:
# ctrl+j == terminal

In [3]:
import numpy as np

In [10]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([8,9,1,2,3,4,5,6,])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 9 1 2 3 4 5 6]


In [11]:
type(a)

numpy.ndarray

In [12]:
print(a+b)
print(a-b)
print(a*b)

[ 9 11  4  6  8 10 12 14]
[-7 -7  2  2  2  2  2  2]
[ 8 18  3  8 15 24 35 48]
