In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([5,4,3])
print(a)
print(b)

[1 2 3]
[5 4 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a=np.array(1,2,3)
b=np.array([5,4,3])
print(a)
print(b)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [6]:
type(a)

numpy.ndarray

Basic Opretations of array:

In [7]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6]
[-4 -2  0]
[5 8 9]


In [8]:
# CREATING 2D ARRAY:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
type(arr)

numpy.ndarray

In [13]:
#CREATING 3D ARRAY:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
print(arr.shape)

(2, 3)


In [17]:
print(arr2.shape)

(1, 3, 3)


In [18]:
print(arr.dtype)

int64


In [21]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [23]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [24]:
np.random.randint(10.30,size=(3,3))

array([[9, 5, 0],
       [5, 5, 2],
       [2, 6, 3]], dtype=int32)

In [25]:
x=np.array([[7,2,3],[2,5,2],[3,5,1]])
y=np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)

print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [26]:
print(x+y)
print(x-y)
print(x*y)


[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  0]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [27]:
# if i want matrix multiplication:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
# another method of multiplication:
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [29]:
#3rd another method:
print(x.dot(y))
np.dot(x,y)


[[19 85 34]
 [21 61 22]
 [20 64 22]]


array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [30]:
x.prod()#product of all elements in the array

np.int64(12600)

In [31]:
x.mean()

np.float64(3.3333333333333335)

In [32]:
round(x.mean())# rounding the mean value

3

In [33]:
x.mean(axis=0)# mean along the first axis(colunms)

array([4., 4., 2.])

In [36]:
x.mean(axis=1)#mean along the second axis(rows)


array([4., 3., 3.])

In [37]:
print(x.sum())# sum of all elements in the array
print(x.var())# variance of all elements in the array
print(x.std())# standard deviation of all elements in the array

30
3.3333333333333335
1.8257418583505538


In [38]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))#median
print(np.percentile(a,25))
print(np.percentile(a,75))#interquartile range

5.0
3.0
7.0


In [39]:
b=np.random.randint(11,100,(4,4))
print(b)

[[23 86 95 85]
 [70 54 59 35]
 [77 21 57 94]
 [59 33 14 24]]
